version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /src/app.py 0.0.0.0:9888
    volumes:
      - .:/code
    ports:
      - 9888:9888
    depends_on:
      - db

volumes:
  postgres_data: