version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: vatevr/cybathlon-recordings
    volumes:
      - .:/src
    ports:
      - 9888:9888
    depends_on:
      - db

volumes:
  postgres_data: