version: '3.7'

services:
  db:
    container_name: postgres
    image: postgres:10.1-alpine
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    networks:
      - cybathlon
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      TEST: test_value
      DBUSER: postgres
      DBPASSWORD: docker
      DBHOST: postgres
      DBPORT: 5434
    volumes:
      - .:/src
    networks:
      - cybathlon
    ports:
      - 9888:9888
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  cybathlon:
    driver: bridge


